# Generated by Django 4.0.4 on 2022-04-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0008_alter_basket_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketManager',
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('id',)},
        ),
    ]
