# Generated by Django 3.2.8 on 2022-03-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0006_auto_20220328_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('quantity',)},
        ),
    ]
