# Generated by Django 3.2.8 on 2022-03-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0007_alter_basket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('-quantity',)},
        ),
    ]
